### ISSUE TITLE
Stuck in "Copying assets"

### ISSUE THREAD

**Issue by taralx** [AndProx/AndProx#11]
My USB port isn't great and the proxmark sometimes disconnects mid-operation. If I hit the back button to get back to the connect button, it sometimes pops up with "Copying assets" forever...

**Comment by taralx** [comment]
Nothing obvious in logcat.

**Comment by taralx** [comment]
```
03-06 13:26:06.950 21308 21750 E NativeSerialWrapper: IOException in send
03-06 13:26:06.950 21308 21750 E NativeSerialWrapper: java.io.IOException: Error writing 544 bytes at offset 0 length=544
03-06 13:26:06.950 21308 21750 E NativeSerialWrapper:   at com.hoho.android.usbserial.driver.CdcAcmSerialDriver$CdcAcmSerialPort.write(CdcAcmSerialDriver.java:312)
03-06 13:26:06.950 21308 21750 E NativeSerialWrapper:   at au.id.micolous.andprox.natives.NativeSerialWrapper.send(NativeSerialWrapper.java:56)
```

**Comment by micolous** [comment]
That log message is not related to the issue.  But that message happens if pm3client has tried to talk to PM3, and it was no longer able to talk to your PM3 -- which would fit your USB port issue.

I've done a fair bit of work on AndProx since the last release (that's in the `master` branch).  They may resolve the "copying assets" issue... as I haven't had that come up again for me lately.  They also handle USB disconnection a little better.

Unfortunately, with a bad USB connection -- there's always a chance that the PM3's microcontroller has lost power and reset, so the safest thing for the program to do is stop accepting new commands.

I'm currently holding off a new release as I'm waiting for some patches to be accepted into upstream Proxmark3 (and a stable release), and there's a couple of UI issues on the Android side that I want to resolve.

**Comment by micolous** [comment]
Looks like I haven't fixed it -- I've had this happen for me again on current master. Unfortunately the application wasn't running in debug mode, and there was also not obvious log entry that pointed out a possible cause.

The way that the `CopyTask` is set up shouldn't allow it to keep the "copying assets" dialog hanging there.

I need a way to reliably reproduce this and catch it while running the debugger to see what's going on here.
